[config]
version_check = false

[templates.hyprlaxmisc]
input_path = './templates/misc.kdl'
output_path = '~/.config/niri/misc.kdl'
post_hook = 'pkill hyprlax && hyprlax {{image}} & disown'

[templates.gtk3]
input_path = './templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-dark'

[templates.gtk4]
input_path = './templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'
post_hook = 'gsettings set org.gnome.desktop.interface icon-theme Deepin2022-Dark'

[templates.color-scheme]
input_path = './templates/Matugen.colors'
output_path = '~/.local/share/color-schemes/Matugen.colors'

[templates.vscode] # hyprluna
input_path = "./templates/hyprlunavsc.json"
output_path = "~/.vscode-oss/extensions/hyprluna.hyprluna-theme-1.0.2/themes/hyprluna.json"

[templates.kitty]
input_path = './templates/kitty-colors.conf'
output_path = '~/.config/kitty/colors.conf'
post_hook = 'pkill -SIGUSR1 kitty'

[templates.pywalfox]
input_path = './templates/pywalfox-colors.json'
output_path = '~/.cache/wal/colors.json'
post_hook = 'pywalfox update'

[templates.helix]
input_path = './templates/helix.toml'
output_path = '~/.config/helix/themes/matugen.toml'

[templates.starship]
input_path = './templates/starship.toml'
output_path = '~/.config/starship.toml'

[templates.fuzzel]
input_path = './templates/fuzzel.ini'
output_path = '~/.config/fuzzel/colors.ini'

[templates.hyprlock]
input_path = './templates/hyprlock.conf'
output_path = '~/.config/hypr/hyprlock.conf'
