# Don't print a new line at the start of the prompt
add_newline = true

format = """
$cmd_duration ó°œ¥ $directory $git_branch
$character
"""

# ================= Character =================

[character]
success_symbol = "[  î©± ï‹](bold fg:blue)"
error_symbol   = "[  ï€ ï‹](bold fg:red)"

# ================= Package =================

[package]
disabled = true

# ================= Git =================

[git_branch]
symbol = "ó°˜¬"
truncation_length = 12
truncation_symbol = ""
style = "fg:cyan"
format = "ó°œ¥ [ $symbol $branch(:$remote_branch) ](bold fg:cyan)"

[git_commit]
commit_hash_length = 4
tag_symbol = "ï’¶ "

[git_state]
format = '[($state $progress_current/$progress_total)](fg:yellow) '
cherry_pick = "[PICKING](bold red)"

[git_status]
conflicted = " ğŸ³ "
ahead      = " ğŸğŸ’¨ "
behind     = " ğŸ˜° "
diverged   = " ğŸ˜µ "
untracked  = " ğŸ¤· "
stashed    = " ğŸ“¦ "
modified   = " ğŸ“ "
staged     = '[++($count)](green)'
renamed    = " âœï¸ "
deleted    = " ğŸ—‘ "

# ================= Host =================

[hostname]
ssh_only = false
disabled = false
trim_at = ".companyname.com"
format = "[â€¢$hostname](bold fg:black bg:cyan)[î‚´](bold fg:cyan)"

# ================= User =================

[username]
show_always = true
disabled = false
style_user = "bold fg:black bg:cyan"
style_root = "bold fg:white bg:red"
format = "[î‚¶](bold fg:cyan)[$user]($style)"

# ================= Directory =================

[directory]
home_symbol = " ï‘­ "
read_only = " ï‘– "
truncation_length = 6
truncation_symbol = " â€¢â€¢/"
style = "bold fg:blue"
format = "[ó°‰‹ $path](bold fg:blue)"

[directory.substitutions]
"Desktop"   = " ï’© "
"Documents" = " ï’¥ "
"Downloads" = " ï‰ "
"Music"     = " ó°ˆ "
"Pictures"  = " ï "
"Videos"    = " ï”¬ "
"GitHub"    = " ó°Š¤ "

# ================= Cmd Duration =================

[cmd_duration]
min_time = 0
format = "[ Time: ](bold fg:yellow)[ó°ª¢ $duration](bold fg:yellow)"

# ================= Line break =================

[line_break]
disabled = false

# ================= Memory / Time =================

[memory_usage]
disabled = true

[time]
disabled = true
